name: pas1_mobile_11pplg1_30
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  motion_tab_bar_v2: ^0.3.0
  get_storage: ^2.1.1
  http: ^1.1.0
  sqflite: ^2.3.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
